### ISSUE TITLE
Missing Descr field on Transfer / Burn Withdraw Funds (Transfer)

### ISSUE THREAD

**Issue by marc-queiroz** [Fairlay/Bitcoin-Betting#13]
When reviewing the Docs for Burn Withdraw Funds, I couldn't find the Descr field on example. Is the Reference field the correct one? Thanks.

**Comment by Bitcoin-Betting-Official** [comment]
There is no "Descr".  It is called "Reference"  which can contain arbitrary text. For Burn Request it must only contain the address on the target chain.   For example "Reference": "0x63c3633207A1400868b05e776c26E77284B9ebC1",
