### ISSUE TITLE
Competitions Subscription needs to return  Number of markets

### ISSUE THREAD

**Issue by Bitcoin-Betting-Official** [Fairlay/Bitcoin-Betting#6]

**Comment by caravan1723** [comment]
the competition data is now returned as a collection of [ <CompetitionName>: <NumberOfMarkets> ]

**Comment by caravan1723** [comment]
{
    "State": "Success",

    "Type": "SubscribeCompetitions",

    "Data": {
        "1": {
            { "Sweden - 2nd Div. Sodra Svealand": 4 },
            { "Ireland - Premier Corners": 5 },
        },
        "2": {
            { "ITF Women Ceska Lipa - QF": 3 },
        },
        "12": {
            { "Australia - NBL1 Women": 2 },
            { "New Zealand - NBL": 6 }
        },
        "35": {}
    }
    // Dict where key is category ID with an array of competition names
}
